### ISSUE TITLE
Use internal tagging for better query ergonomics

### ISSUE THREAD

**Issue by ysimonson** [braidery/braid-lib#11]
See "Internally Tagged" section here: https://serde.rs/enum-representations.html

We could use this on queries to make them more natural-looking. This will likely require changes to bin as well.

**Comment by jasonwyatt** [comment]
I like the "untagged" option there, it seems less verbose and might produce nicer JSON that exposes less of the internal design for the structs (like the actual name).

**Comment by ysimonson** [comment]
Yeah that makes sense. I'll give that a shot.

Progress is on this branch: https://github.com/braidery/braid-lib/tree/feature/better-queries

**Comment by ysimonson** [comment]
This was merged in earlier; forgot to close this ticket
